sudo: required
dist: trusty

language: c
cache: ccache

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-4.9
      env:
        - CXX=g++-4.9 CC=gcc-4.9 MODE=Debug
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - cmake
            - clang-3.6
      env:
        - CXX=clang++-3.6 CC=clang-3.6 MODE=Debug
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-4.9
      env:
        - CXX=g++-4.9 CC=gcc-4.9 MODE=Release
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - cmake
            - clang-3.6
      env:
        - CXX=clang++-3.6 CC=clang-3.6 MODE=Release

install:
  - pip install --user pyyaml
  - pip install --user poster

script:
  - ./cmaki/run.sh $MODE
  - |
    if [[ $CXX == "g++-4.9" && $MODE == "Release" ]]; then
        (cd cmaki_generator && ./build github://$TRAVIS_REPO_SLUG -o --server=http://artifacts.myftp.biz:8080)
    fi

