version: 0.1.{build}

platform:
  - x64

install:
  - cmd: git submodule update --init --recursive
  - cmd: pip install pyyaml
  - cmd: pip install poster

build_script:
  - cmd: cd cmaki && git pull origin master && cd ..
  - cmd: cd cmaki_generator && git pull origin master && cd ..
  - cmd: mkdir release
  - cmd: cd release
  - cmd: cmake .. -DCMAKE_BUILD_TYPE=Release -DFIRST_ERROR=1 -G "Visual Studio 14 2015 Win64"
  - cmd: cmake --build . --config Release --target install

test_script:
  - cmd: ctest . --no-compress-output --output-on-failure -T Test -C Release -V

on_success:
    - cmd: cd cmaki_generator && build fast-event-system --server=http://artifacts.myftp.biz:8080 && cd ..
