version: 1.0.0.{build}

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

build: off
install:
  - ps:
    |
      $source = "https://raw.githubusercontent.com/makiolo/cmaki/master/ci.cmd"
      $dest = $env:TEMP + "\ci.cmd"
      $WebClient = New-Object System.Net.WebClient
      $WebClient.DownloadFile($source, $dest)
      Invoke-Expression $dest
      if($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode ) }
